name: Release Build

on:
  push:
    tags:
      - 'v*'  # Only runs when a version tag like v1.0.0 is pushed

jobs:
  build:
    name: Build for All Platforms
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Create build directory
        run: mkdir -p build

      - name: Build for Linux (amd64)
        run: |
          GOOS=linux GOARCH=amd64 go build -o build/simpletodo-linux ./app

      - name: Build for Windows (amd64)
        run: |
          GOOS=windows GOARCH=amd64 go build -o build/simpletodo-windows.exe ./app

      - name: Build for macOS (Intel)
        run: |
          GOOS=darwin GOARCH=amd64 go build -o build/simpletodo-macos-amd64 ./app

      - name: Build for macOS (Apple Silicon)
        run: |
          GOOS=darwin GOARCH=arm64 go build -o build/simpletodo-macos-arm64 ./app

      - name: Build for Android (arm64)
        run: |
          GOOS=android GOARCH=arm64 go build -o build/simpletodo-android-arm64 ./app

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/simpletodo-linux
            build/simpletodo-windows.exe
            build/simpletodo-macos-amd64
            build/simpletodo-macos-arm64
            build/simpletodo-android-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
