name: Build Go Binaries

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build for All Platforms
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o build/simpletodo-linux ./app

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o build/simpletodo-windows.exe ./app

      - name: Build for macOS
        run: |
          GOOS=darwin GOARCH=amd64 go build -o build/simpletodo-macos ./app

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: simpletodo-binaries
          path: build/
